# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/all_distance_sketch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/all_distance_sketch.proto',
  package='all_distance_sketch.proto',
  serialized_pb='\n\x1fproto/all_distance_sketch.proto\x12\x19\x61ll_distance_sketch.proto\"\xd5\x02\n\x13SingleNodeSketchGpb\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x16\n\x0enode_random_id\x18\x02 \x01(\x01\x12\\\n\x0enode_in_sketch\x18\x03 \x03(\x0b\x32\x44.all_distance_sketch.proto.SingleNodeSketchGpb.NodeSummaryDetailsGpb\x12J\n\x07z_value\x18\x04 \x03(\x0b\x32\x39.all_distance_sketch.proto.SingleNodeSketchGpb.ZValuesGpb\x1a:\n\x15NodeSummaryDetailsGpb\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x1a/\n\nZValuesGpb\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\"\x9a\x03\n\x14\x41llDistanceSketchGpb\x12W\n\rconfiguration\x18\x01 \x01(\x0b\x32@.all_distance_sketch.proto.AllDistanceSketchGpb.ConfigurationGpb\x12\x46\n\x0enodes_sketches\x18\x02 \x03(\x0b\x32..all_distance_sketch.proto.SingleNodeSketchGpb\x12Y\n\x0fnode_thresholds\x18\x03 \x03(\x0b\x32@.all_distance_sketch.proto.AllDistanceSketchGpb.NodeThresholdGpb\x1aI\n\x10NodeThresholdGpb\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x11\n\tthreshold\x18\x02 \x01(\x01\x12\x11\n\trandom_id\x18\x03 \x01(\x01\x1a;\n\x10\x43onfigurationGpb\x12\t\n\x01k\x18\x01 \x01(\x04\x12\x1c\n\x14should_calc_z_values\x18\x02 \x01(\x08')




_SINGLENODESKETCHGPB_NODESUMMARYDETAILSGPB = _descriptor.Descriptor(
  name='NodeSummaryDetailsGpb',
  full_name='all_distance_sketch.proto.SingleNodeSketchGpb.NodeSummaryDetailsGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.NodeSummaryDetailsGpb.node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.NodeSummaryDetailsGpb.distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=297,
  serialized_end=355,
)

_SINGLENODESKETCHGPB_ZVALUESGPB = _descriptor.Descriptor(
  name='ZValuesGpb',
  full_name='all_distance_sketch.proto.SingleNodeSketchGpb.ZValuesGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.ZValuesGpb.node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='distance', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.ZValuesGpb.distance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=357,
  serialized_end=404,
)

_SINGLENODESKETCHGPB = _descriptor.Descriptor(
  name='SingleNodeSketchGpb',
  full_name='all_distance_sketch.proto.SingleNodeSketchGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_random_id', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.node_random_id', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_in_sketch', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.node_in_sketch', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_value', full_name='all_distance_sketch.proto.SingleNodeSketchGpb.z_value', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SINGLENODESKETCHGPB_NODESUMMARYDETAILSGPB, _SINGLENODESKETCHGPB_ZVALUESGPB, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=63,
  serialized_end=404,
)


_ALLDISTANCESKETCHGPB_NODETHRESHOLDGPB = _descriptor.Descriptor(
  name='NodeThresholdGpb',
  full_name='all_distance_sketch.proto.AllDistanceSketchGpb.NodeThresholdGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.NodeThresholdGpb.node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.NodeThresholdGpb.threshold', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='random_id', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.NodeThresholdGpb.random_id', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=683,
  serialized_end=756,
)

_ALLDISTANCESKETCHGPB_CONFIGURATIONGPB = _descriptor.Descriptor(
  name='ConfigurationGpb',
  full_name='all_distance_sketch.proto.AllDistanceSketchGpb.ConfigurationGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='k', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.ConfigurationGpb.k', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='should_calc_z_values', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.ConfigurationGpb.should_calc_z_values', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=758,
  serialized_end=817,
)

_ALLDISTANCESKETCHGPB = _descriptor.Descriptor(
  name='AllDistanceSketchGpb',
  full_name='all_distance_sketch.proto.AllDistanceSketchGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='configuration', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.configuration', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodes_sketches', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.nodes_sketches', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_thresholds', full_name='all_distance_sketch.proto.AllDistanceSketchGpb.node_thresholds', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ALLDISTANCESKETCHGPB_NODETHRESHOLDGPB, _ALLDISTANCESKETCHGPB_CONFIGURATIONGPB, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=407,
  serialized_end=817,
)

_SINGLENODESKETCHGPB_NODESUMMARYDETAILSGPB.containing_type = _SINGLENODESKETCHGPB;
_SINGLENODESKETCHGPB_ZVALUESGPB.containing_type = _SINGLENODESKETCHGPB;
_SINGLENODESKETCHGPB.fields_by_name['node_in_sketch'].message_type = _SINGLENODESKETCHGPB_NODESUMMARYDETAILSGPB
_SINGLENODESKETCHGPB.fields_by_name['z_value'].message_type = _SINGLENODESKETCHGPB_ZVALUESGPB
_ALLDISTANCESKETCHGPB_NODETHRESHOLDGPB.containing_type = _ALLDISTANCESKETCHGPB;
_ALLDISTANCESKETCHGPB_CONFIGURATIONGPB.containing_type = _ALLDISTANCESKETCHGPB;
_ALLDISTANCESKETCHGPB.fields_by_name['configuration'].message_type = _ALLDISTANCESKETCHGPB_CONFIGURATIONGPB
_ALLDISTANCESKETCHGPB.fields_by_name['nodes_sketches'].message_type = _SINGLENODESKETCHGPB
_ALLDISTANCESKETCHGPB.fields_by_name['node_thresholds'].message_type = _ALLDISTANCESKETCHGPB_NODETHRESHOLDGPB
DESCRIPTOR.message_types_by_name['SingleNodeSketchGpb'] = _SINGLENODESKETCHGPB
DESCRIPTOR.message_types_by_name['AllDistanceSketchGpb'] = _ALLDISTANCESKETCHGPB

class SingleNodeSketchGpb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class NodeSummaryDetailsGpb(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SINGLENODESKETCHGPB_NODESUMMARYDETAILSGPB

    # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.SingleNodeSketchGpb.NodeSummaryDetailsGpb)

  class ZValuesGpb(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SINGLENODESKETCHGPB_ZVALUESGPB

    # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.SingleNodeSketchGpb.ZValuesGpb)
  DESCRIPTOR = _SINGLENODESKETCHGPB

  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.SingleNodeSketchGpb)

class AllDistanceSketchGpb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class NodeThresholdGpb(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ALLDISTANCESKETCHGPB_NODETHRESHOLDGPB

    # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.AllDistanceSketchGpb.NodeThresholdGpb)

  class ConfigurationGpb(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ALLDISTANCESKETCHGPB_CONFIGURATIONGPB

    # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.AllDistanceSketchGpb.ConfigurationGpb)
  DESCRIPTOR = _ALLDISTANCESKETCHGPB

  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.AllDistanceSketchGpb)


# @@protoc_insertion_point(module_scope)
