# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cover.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/cover.proto',
  package='all_distance_sketch.proto',
  serialized_pb='\n\x11proto/cover.proto\x12\x19\x61ll_distance_sketch.proto\"5\n\x0bSeedInfoGpb\x12\x14\n\x0cseed_node_id\x18\x01 \x01(\x04\x12\x10\n\x08node_ids\x18\x02 \x03(\x04\"A\n\x08\x43overGpb\x12\x35\n\x05seeds\x18\x01 \x03(\x0b\x32&.all_distance_sketch.proto.SeedInfoGpb')




_SEEDINFOGPB = _descriptor.Descriptor(
  name='SeedInfoGpb',
  full_name='all_distance_sketch.proto.SeedInfoGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed_node_id', full_name='all_distance_sketch.proto.SeedInfoGpb.seed_node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_ids', full_name='all_distance_sketch.proto.SeedInfoGpb.node_ids', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=48,
  serialized_end=101,
)


_COVERGPB = _descriptor.Descriptor(
  name='CoverGpb',
  full_name='all_distance_sketch.proto.CoverGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seeds', full_name='all_distance_sketch.proto.CoverGpb.seeds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=168,
)

_COVERGPB.fields_by_name['seeds'].message_type = _SEEDINFOGPB
DESCRIPTOR.message_types_by_name['SeedInfoGpb'] = _SEEDINFOGPB
DESCRIPTOR.message_types_by_name['CoverGpb'] = _COVERGPB

class SeedInfoGpb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEEDINFOGPB

  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.SeedInfoGpb)

class CoverGpb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _COVERGPB

  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.CoverGpb)


# @@protoc_insertion_point(module_scope)
