# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/embedding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/embedding.proto',
  package='all_distance_sketch.proto',
  serialized_pb=_b('\n\x15proto/embedding.proto\x12\x19\x61ll_distance_sketch.proto\":\n\x10NodeEmbeddingGpb\x12\x14\n\x0cseed_node_id\x18\x01 \x01(\x04\x12\x10\n\x08node_ids\x18\x02 \x03(\x01\"J\n\x0c\x45mbeddingGpb\x12:\n\x05seeds\x18\x01 \x03(\x0b\x32+.all_distance_sketch.proto.NodeEmbeddingGpb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NODEEMBEDDINGGPB = _descriptor.Descriptor(
  name='NodeEmbeddingGpb',
  full_name='all_distance_sketch.proto.NodeEmbeddingGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seed_node_id', full_name='all_distance_sketch.proto.NodeEmbeddingGpb.seed_node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_ids', full_name='all_distance_sketch.proto.NodeEmbeddingGpb.node_ids', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=110,
)


_EMBEDDINGGPB = _descriptor.Descriptor(
  name='EmbeddingGpb',
  full_name='all_distance_sketch.proto.EmbeddingGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seeds', full_name='all_distance_sketch.proto.EmbeddingGpb.seeds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=186,
)

_EMBEDDINGGPB.fields_by_name['seeds'].message_type = _NODEEMBEDDINGGPB
DESCRIPTOR.message_types_by_name['NodeEmbeddingGpb'] = _NODEEMBEDDINGGPB
DESCRIPTOR.message_types_by_name['EmbeddingGpb'] = _EMBEDDINGGPB

NodeEmbeddingGpb = _reflection.GeneratedProtocolMessageType('NodeEmbeddingGpb', (_message.Message,), dict(
  DESCRIPTOR = _NODEEMBEDDINGGPB,
  __module__ = 'proto.embedding_pb2'
  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.NodeEmbeddingGpb)
  ))
_sym_db.RegisterMessage(NodeEmbeddingGpb)

EmbeddingGpb = _reflection.GeneratedProtocolMessageType('EmbeddingGpb', (_message.Message,), dict(
  DESCRIPTOR = _EMBEDDINGGPB,
  __module__ = 'proto.embedding_pb2'
  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.EmbeddingGpb)
  ))
_sym_db.RegisterMessage(EmbeddingGpb)


# @@protoc_insertion_point(module_scope)
