# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/embedding.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/embedding.proto',
  package='all_distance_sketch.proto',
  serialized_pb='\n\x15proto/embedding.proto\x12\x19\x61ll_distance_sketch.proto\"7\n\x10NodeEmbeddingGpb\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x12\n\ncoordinate\x18\x02 \x03(\x01\"J\n\x0c\x45mbeddingGpb\x12:\n\x05nodes\x18\x01 \x03(\x0b\x32+.all_distance_sketch.proto.NodeEmbeddingGpb')




_NODEEMBEDDINGGPB = _descriptor.Descriptor(
  name='NodeEmbeddingGpb',
  full_name='all_distance_sketch.proto.NodeEmbeddingGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='all_distance_sketch.proto.NodeEmbeddingGpb.node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coordinate', full_name='all_distance_sketch.proto.NodeEmbeddingGpb.coordinate', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=52,
  serialized_end=107,
)


_EMBEDDINGGPB = _descriptor.Descriptor(
  name='EmbeddingGpb',
  full_name='all_distance_sketch.proto.EmbeddingGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodes', full_name='all_distance_sketch.proto.EmbeddingGpb.nodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=109,
  serialized_end=183,
)

_EMBEDDINGGPB.fields_by_name['nodes'].message_type = _NODEEMBEDDINGGPB
DESCRIPTOR.message_types_by_name['NodeEmbeddingGpb'] = _NODEEMBEDDINGGPB
DESCRIPTOR.message_types_by_name['EmbeddingGpb'] = _EMBEDDINGGPB

class NodeEmbeddingGpb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NODEEMBEDDINGGPB

  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.NodeEmbeddingGpb)

class EmbeddingGpb(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EMBEDDINGGPB

  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.EmbeddingGpb)


# @@protoc_insertion_point(module_scope)
