# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ranking.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/ranking.proto',
  package='all_distance_sketch.proto',
  serialized_pb=_b('\n\x13proto/ranking.proto\x12\x19\x61ll_distance_sketch.proto\"1\n\x0bNodeRankGpb\x12\x0f\n\x07node_id\x18\x01 \x01(\x04\x12\x11\n\tnode_rank\x18\x02 \x01(\x04\"w\n\x0cNodeRanksGpb\x12\x16\n\x0esource_node_id\x18\x01 \x01(\x04\x12\x13\n\x0bmax_node_id\x18\x02 \x01(\x04\x12:\n\nnode_ranks\x18\x03 \x03(\x0b\x32&.all_distance_sketch.proto.NodeRankGpb')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NODERANKGPB = _descriptor.Descriptor(
  name='NodeRankGpb',
  full_name='all_distance_sketch.proto.NodeRankGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='all_distance_sketch.proto.NodeRankGpb.node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_rank', full_name='all_distance_sketch.proto.NodeRankGpb.node_rank', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=99,
)


_NODERANKSGPB = _descriptor.Descriptor(
  name='NodeRanksGpb',
  full_name='all_distance_sketch.proto.NodeRanksGpb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_node_id', full_name='all_distance_sketch.proto.NodeRanksGpb.source_node_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_node_id', full_name='all_distance_sketch.proto.NodeRanksGpb.max_node_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_ranks', full_name='all_distance_sketch.proto.NodeRanksGpb.node_ranks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=220,
)

_NODERANKSGPB.fields_by_name['node_ranks'].message_type = _NODERANKGPB
DESCRIPTOR.message_types_by_name['NodeRankGpb'] = _NODERANKGPB
DESCRIPTOR.message_types_by_name['NodeRanksGpb'] = _NODERANKSGPB

NodeRankGpb = _reflection.GeneratedProtocolMessageType('NodeRankGpb', (_message.Message,), dict(
  DESCRIPTOR = _NODERANKGPB,
  __module__ = 'proto.ranking_pb2'
  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.NodeRankGpb)
  ))
_sym_db.RegisterMessage(NodeRankGpb)

NodeRanksGpb = _reflection.GeneratedProtocolMessageType('NodeRanksGpb', (_message.Message,), dict(
  DESCRIPTOR = _NODERANKSGPB,
  __module__ = 'proto.ranking_pb2'
  # @@protoc_insertion_point(class_scope:all_distance_sketch.proto.NodeRanksGpb)
  ))
_sym_db.RegisterMessage(NodeRanksGpb)


# @@protoc_insertion_point(module_scope)
